### ISSUE TITLE
Can't find imagenet_mean_227.binaryproto

### ISSUE THREAD

**Issue by KranthiGV** [fartashf/under_convnet#1]
Hello,
I'm not able to find the file imagenet_mean_227.binaryproto
I tried searching for it in the caffenet repo, too.
It had different dimensions. I resized it into (3,227,227) but then I am not able to reproduce your results.

> Initial euclidean distance: 154.6842
> Final euclidean distance: 8.2734

Can you share your version of the file?
Thank you

**Comment by fartashf** [comment]
Thanks for reporting. I added it in 4aaca07.

**Comment by KranthiGV** [comment]
Thank you. I'm currently able to reproduce it.

**Comment by fartashf** [comment]
Awesome. I'm closing this issue but please let us know if you found any other issues.
